---
- name: Check RAM memory and set vm.swappiness
  hosts: localhost
  become: true
  become_user: root
  tasks:
  - name: get free memory size and convert it to int
    set_fact:
     mem_size: "{{ ansible_memtotal_mb | int }}"
  - name: show memsize
    debug: 
     var: "{{ mem_size }}"
  - name: Set vm.swappines to 10 if ram > 2048
    sysctl:
     name: vm.swappiness
     value: 10
     sysctl_set: yes
     state: present
    when: mem_size | int > 2048
  - name: Display error message when mem_size < 2048MB
    debug:
     msg: "Server memory less than 2048MB"
    when: mem_size | int < 2048
