---
- name: Create users
  hosts: all
  become: true
  become_user: root
  vars_files:
   - secret.yaml
   - vars/user_list.yml
  tasks:
  - name: create users on webservers hostgroup
    user:
     name: "{{ item.username }}"
     uid: "{{ item.uid }}"
     password: pwd.msg
     password: "{{ '{{ user_password }}' | password_hash('sha512', 'examsalt') }}"
     groups: wheel
     append: yes
     shell: /bin/bash
    when: " 'webservers' in group_names and (item.uid|int) < 2000"
    loop: "{{ users }}"

  - name: create users on database host groups
    user:
     name: "{{ item.username }}"
     uid: "{{ item.uid }}"
     password: pwd.msg
     password: "{{ '{{ user_password }}' | password_hash('sha512', 'examsalt') }}"
     groups: wheel
     append: yes
     shell: /bin/bash
    when: "'database' in group_names and (item.uid|string)[0]=='2'"
    loop: "{{ users }}"


